format = """
 [](fg:#1a374d)\
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$container\
$docker_context\
$cmd_duration
 $character
"""
[os]
disabled = false
style = "bg:#1a374d fg:#FFFFFF bold"
format = "[$symbol ]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = ""
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
style_user = "bg:#1A374D fg:#FFFFFF bold"
style_root = "bg:#1A374D fg:red bold"
format = "[ $user ]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 10_000
truncate_to_repo = false
style = "fg:#FFFFFF bold bg:#406882"
format = "[](bg:#406882 fg:#1A374D)[ $path ]($style)[$read_only]($read_only_style)"

[hostname]
ssh_only = false
format = "[$ssh_symbol](bg:#1A374D fg:#FFFFFF bold)[on ](bg:#1A374D fg:#ff914d bold)[$hostname ](bg:#1A374D fg:#FFFFFF bold)"

[git_branch]
# format = "[ $symbol](fg:#F7FF93 bold bg:#6998AB)[ $branch (:$remote_branch) ]($style)"
format = "[](bg:#6998AB fg:#406882)[ $symbol](fg:#ff914d bold bg:#6998AB)[ $branch (:$remote_branch) ]($style)[](fg:#6998AB bg:#87b7cf)"
style = "fg:#FFFFFF bold bg:#6998AB"

[git_status]
format = ' \[$all_status $ahead_behind\](fg:#ffed85 bold bg:#87b7cf)[ ](fg:#87b7cf)'
up_to_date = ' [UPTODATE](fg:#ffed85 bold bg:#87b7cf'
behind = ' [$count BIHIND](fg:#e67e22 bold bg:#87b7cf)'
ahead = ' [$count AHEAD](fg:#d64040 bold bg:#87b7cf)'
modified = ' [$count MODIFIED](fg:#e67e22 bold bg:#87b7cf)'
staged = ' [$count STAGING](fg:#a6e3a1 bold bg:#87b7cf)'

[character]
success_symbol = "[⟩](fg:#e67e22)[⟩](fg:#ffed85 )"
error_symbol = "[✘ ](fg:red bold)"

[container]
disabled = false
style = "bg:color_orange fg:color_fg0"

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"
