[tools]
# -- Cores
node = "22"
deno = "latest"
python = "3.12"
rust = "latest"

# -- Tools
uv = "latest"
aws-cli = "latest"

# vim = "latest"  # macでうまく入らないので
"asdf:mise-plugins/mise-tmux" = "latest"


[settings]
python.uv_venv_auto = true
