version: '3'
services:
  local:
    build:
       context: ..
       dockerfile: ./Dockerfile
    image: local-dev-for-nvim
    container_name: local-container-for-nvim
    tty: true
    stdin_open: true
    command: >
      sh -c 'git clone git@github.com:daikichiba9511/dotfiles.git ~/dotfiles && cd ~/dotfiles && sh scripts/setup.sh y'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [utility, compute, video]
    volumes:
      - .:/workspace/working
      - ${HOME}/.config:/root/.config
      - ${HOME}/.config/nvim/init.vim:/root/.config/nvim/init.vim
      - ${HOME}/.zshrc:/root/.zshrc
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.ssh/:/root/.ssh
